{
    "status": "failed",
    "message": "An error occurred: Length mismatch: Expected axis has 16 elements, new values have 14 elements\n\nTraceback (most recent call last):\n  File \"C:\\Users\\tamilarasans\\Desktop\\REPORT\\dlc_reports\\nrldc_app\\management\\commands\\nrldc_project.py\", line 93, in handle\n    self.extract_tables_from_pdf(pdf_path, output_dir, target_date)\n  File \"C:\\Users\\tamilarasans\\Desktop\\REPORT\\dlc_reports\\nrldc_app\\management\\commands\\nrldc_project.py\", line 173, in extract_tables_from_pdf\n    sub_2A = self.extract_subtable_by_markers(all_content_df, r\".*2\\s*\\(A\\)\\s*State's\\s*Load\\s*Deails.*\", r\"2\\s*\\(B\\).*\", header_row_count=2, debug_table_name=\"Table 2(A)\")\n  File \"C:\\Users\\tamilarasans\\Desktop\\REPORT\\dlc_reports\\nrldc_app\\management\\commands\\nrldc_project.py\", line 140, in extract_subtable_by_markers\n    sub_df_data.columns = new_columns[:len(sub_df_data.columns)]\n  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pandas\\core\\generic.py\", line 6218, in __setattr__\n    return object.__setattr__(self, name, value)\n  File \"properties.pyx\", line 69, in pandas._libs.properties.AxisProperty.__set__\n  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pandas\\core\\generic.py\", line 767, in _set_axis\n    self._mgr.set_axis(axis, labels)\n  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pandas\\core\\internals\\managers.py\", line 227, in set_axis\n    self._validate_set_axis(axis, new_labels)\n  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pandas\\core\\internals\\base.py\", line 85, in _validate_set_axis\n    raise ValueError(\nValueError: Length mismatch: Expected axis has 16 elements, new values have 14 elements\n"
}